// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvkxs2ZT7sJm26V9v2w1xHzSQnUs3acA4',
    appId: '1:306195797804:web:ef23de8a8551748dbe7e89',
    messagingSenderId: '306195797804',
    projectId: 'multi-store-f1857',
    authDomain: 'multi-store-f1857.firebaseapp.com',
    storageBucket: 'multi-store-f1857.appspot.com',
    measurementId: 'G-1P9H0VJEDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtoo5aT4idta7j80Jr1A4DcQF90d-hTs',
    appId: '1:306195797804:android:cbe1b047cb03bd8abe7e89',
    messagingSenderId: '306195797804',
    projectId: 'multi-store-f1857',
    storageBucket: 'multi-store-f1857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklGJvVhe09xwNgvxQvrr7d6oa40-Z8sg',
    appId: '1:306195797804:ios:caea79762dfe1295be7e89',
    messagingSenderId: '306195797804',
    projectId: 'multi-store-f1857',
    storageBucket: 'multi-store-f1857.appspot.com',
    iosClientId: '306195797804-o9fqdl0l90qpmoafj9oa07oo1prnv80r.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSupplierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCklGJvVhe09xwNgvxQvrr7d6oa40-Z8sg',
    appId: '1:306195797804:ios:caea79762dfe1295be7e89',
    messagingSenderId: '306195797804',
    projectId: 'multi-store-f1857',
    storageBucket: 'multi-store-f1857.appspot.com',
    iosClientId: '306195797804-o9fqdl0l90qpmoafj9oa07oo1prnv80r.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSupplierApp',
  );
}
